"use client";

import React, { useEffect, useRef, useState } from "react";
import s from "./page.module.sass";
import MDEditor from "@uiw/react-md-editor";
import Header from "@/components/Header/Header";
import MobileHeader from "@/components/MobileHeader/MobileHeader";

const source = `
# Technology - GPT

<video width="auto" height="auto" controls>
	<source src="http://dsfgeos.cn/videos/GPTS-1.mp4" type="video/mp4">
</video>

Passive source electromagnetic geophysical exploration technology - GPTS can be applied to mineral resources exploration (deep sea oil and gas and other mineral resources), engineering geological survey, hydrogeological survey, geothermal geological survey, geotechnical survey, disaster and environmental monitoring, and deep space exploration.

## Table of Contents

- [Introduction](#introduction)
- [Applications](#applications)
	- [Mineral Resources Exploration](#mineral-resources-exploration)
	- [Engineering Geological Survey](#engineering-geological-survey)
	- [Hydrogeological Survey](#hydrogeological-survey)
	- [Geothermal Geological Survey](#geothermal-geological-survey)
	- [Geotechnical Survey](#geotechnical-survey)
	- [Disaster and Environmental Monitoring](#disaster-and-environmental-monitoring)
	- [Deep Space Exploration](#deep-space-exploration)
- [Advantages](#advantages)
- [How It Works](#how-it-works)

## Introduction

GPTS (Geophysical Passive Technology System) is a cutting-edge technology used in passive source electromagnetic geophysical exploration. It leverages natural electromagnetic fields to probe subsurface structures without the need for active seismic sources. This technology is versatile and can be applied across various domains, including mineral resource exploration, environmental monitoring, and space exploration.

## Applications

### Mineral Resources Exploration

GPTS is instrumental in the exploration of mineral resources such as deep-sea oil and gas, as well as other valuable minerals. Its ability to detect and map subsurface structures helps in identifying potential resource deposits with high precision.

### Engineering Geological Survey

In engineering geological surveys, GPTS provides critical data for infrastructure projects. It helps in understanding the subsurface conditions, which is essential for the design and construction of buildings, bridges, tunnels, and other structures.

### Hydrogeological Survey

For hydrogeological surveys, GPTS aids in the investigation of groundwater resources. It helps in mapping aquifers, identifying groundwater flow paths, and assessing the quantity and quality of groundwater.

### Geothermal Geological Survey

GPTS plays a significant role in geothermal geological surveys by identifying geothermal reservoirs. This information is crucial for the development of geothermal energy projects, providing a sustainable and renewable energy source.

### Geotechnical Survey

In geotechnical surveys, GPTS assists in the analysis of soil and rock properties. This is vital for assessing the stability and suitability of sites for construction and other land-use activities.

### Disaster and Environmental Monitoring

GPTS is used in disaster and environmental monitoring to detect changes in subsurface conditions that may indicate potential hazards such as landslides, earthquakes, and environmental contamination. This technology provides early warning signs and helps in disaster preparedness and mitigation.

### Deep Space Exploration

In deep space exploration, GPTS contributes to the understanding of planetary subsurfaces. It aids in the search for water, minerals, and other resources on other planets and celestial bodies, providing valuable data for space missions.

## Advantages

- **Non-invasive**: GPTS does not require drilling or active seismic sources, making it environmentally friendly and less disruptive.
- **High Precision**: Provides accurate and detailed subsurface images.
- **Cost-effective**: Reduces the need for expensive and time-consuming drilling operations.
- **Versatile**: Applicable across various domains and environments.

## How It Works

GPTS utilizes natural electromagnetic fields generated by the Earth and cosmic sources. By measuring variations in these fields, the technology can infer the properties and structures of subsurface materials. The data collected is processed and interpreted using advanced algorithms to produce detailed geophysical maps.
	`;

function TechnologyGPTS() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  return (
    <div className={s.container}>
      <Header
        isMenuOpen={isMenuOpen}
        setIsMenuOpen={setIsMenuOpen}
      />
      <MobileHeader isMenuOpen={isMenuOpen} />
      <MDEditor.Markdown className={s.markdown} source={source} />
    </div>
  );
}

export default TechnologyGPTS;
